### PR TITLE
Add missing status message to Redis resource CLI

### PR DESCRIPTION
**Pull request by abays**

### CODE REVIEW

**Comment by abays** [comment]
> @abays: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/functional 	[a72917a](https://github.com/openstack-k8s-operators/infra-operator/commit/a72917a01e1ef62d4eefb67f4773eff779b7b27e) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openstack-k8s-operators_infra-operator/303/pull-ci-openstack-k8s-operators-infra-operator-main-functional/1853895911067881472) 	true 	`/test functional`
> ci/prow/infra-operator-build-deploy-kuttl 	[a72917a](https://github.com/openstack-k8s-operators/infra-operator/commit/a72917a01e1ef62d4eefb67f4773eff779b7b27e) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openstack-k8s-operators_infra-operator/303/pull-ci-openstack-k8s-operators-infra-operator-main-infra-operator-build-deploy-kuttl/1853895911155961856) 	true 	`/test infra-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=infra-operator&pr=303). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:abays).

```
{  error occurred handling build src-amd64: could not get build src-amd64: builds.build.openshift.io "src-amd64" not found}
```

/test functional

**Comment by abays** [comment]
> @abays: The following tests **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/functional 	[a72917a](https://github.com/openstack-k8s-operators/infra-operator/commit/a72917a01e1ef62d4eefb67f4773eff779b7b27e) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openstack-k8s-operators_infra-operator/303/pull-ci-openstack-k8s-operators-infra-operator-main-functional/1853895911067881472) 	true 	`/test functional`
> ci/prow/infra-operator-build-deploy-kuttl 	[a72917a](https://github.com/openstack-k8s-operators/infra-operator/commit/a72917a01e1ef62d4eefb67f4773eff779b7b27e) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openstack-k8s-operators_infra-operator/303/pull-ci-openstack-k8s-operators-infra-operator-main-infra-operator-build-deploy-kuttl/1853895911155961856) 	true 	`/test infra-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=infra-operator&pr=303). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:abays).

```
error: build error: Failed to push image: trying to reuse blob sha256:4d5d1cbd7ece41ce278c26338e01e2b82e1861b820ca052da9f3e0b16815358f at destination: pinging container registry quay.rdoproject.org: Get "https://quay.rdoproject.org/v2/": dial tcp 38.129.56.158:443: i/o timeout
```

/test infra-operator-build-deploy-kuttl

**Comment by abays** [comment]
> @abays: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/infra-operator-build-deploy-kuttl 	[a72917a](https://github.com/openstack-k8s-operators/infra-operator/commit/a72917a01e1ef62d4eefb67f4773eff779b7b27e) 	[link](https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openstack-k8s-operators_infra-operator/303/pull-ci-openstack-k8s-operators-infra-operator-main-infra-operator-build-deploy-kuttl/1853929021822210048) 	true 	`/test infra-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=infra-operator&pr=303). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:abays).

```
error: build error: Failed to push image: trying to reuse blob sha256:4d5d1cbd7ece41ce278c26338e01e2b82e1861b820ca052da9f3e0b16815358f at destination: pinging container registry quay.rdoproject.org: Get "https://quay.rdoproject.org/v2/": dial tcp 38.129.56.158:443: i/o timeout
```

/test infra-operator-build-deploy-kuttl

**Review by stuggi — APPROVED** [review]
/lgtm

**Pull request merged**
