### PR TITLE
Bump lib-common to v0.1.0 for the dev preview

### PR DESCRIPTION
**Pull request by stuggi**

### CODE REVIEW

**Comment by stuggi** [comment]
recheck

**Comment by stuggi** [comment]
recheck

**Comment by stuggi** [comment]
```
fatal: [localhost]: FAILED! => {"changed": true, "checksum": "11379dd56c5d4fa37c4316f3a18be96c58a38639", "cmd": 
"/usr/bin/gmake docker-build IMG=38.102.83.79:5001/openstack-k8s-operators/infra-
operator:4c1455cb6339809f9ec974bf320891f2037c07fb", "dest": "/home/zuul/ci-framework-
data/artifacts/ci_make_002_infra-operator_-_call_docker-build.sh", "gid": 1000, "group": "zuul", "md5sum": 
"7b60992bec37e404cc81aa0d24baccc5", "mode": "0755", "msg": "# github.com/openstack-k8s-operators/lib-
common/modules/test/helpers\n/home/zuul/go/pkg/mod/github.com/openstack-k8s-operators/lib-
common/modules/test@v0.1.0/helpers/memcached.go:********@v0.1.0/helpers/memcached.go:89:23: cannot convert 
mc.Spec.Replicas (variable of type *int32) to type int
```

**Comment by gibizer** [comment]
> ```
> fatal: [localhost]: FAILED! => {"changed": true, "checksum": "11379dd56c5d4fa37c4316f3a18be96c58a38639", "cmd": 
> "/usr/bin/gmake docker-build IMG=38.102.83.79:5001/openstack-k8s-operators/infra-
> operator:4c1455cb6339809f9ec974bf320891f2037c07fb", "dest": "/home/zuul/ci-framework-
> data/artifacts/ci_make_002_infra-operator_-_call_docker-build.sh", "gid": 1000, "group": "zuul", "md5sum": 
> "7b60992bec37e404cc81aa0d24baccc5", "mode": "0755", "msg": "# github.com/openstack-k8s-operators/lib-
> common/modules/test/helpers\n/home/zuul/go/pkg/mod/github.com/openstack-k8s-operators/lib-
> common/modules/test@v0.1.0/helpers/memcached.go:********@v0.1.0/helpers/memcached.go:89:23: cannot convert 
> mc.Spec.Replicas (variable of type *int32) to type int
> ```

wondering how could I reproduce this locally as normal build / test works OK

**Comment by stuggi** [comment]
```
$ /usr/bin/gmake docker-build IMG=quay.io/mschuppe/infra-operator:4c1455cb6339809f9ec974bf320891f2037c07fb
test -f go.work || go work init
go work use .
go work use ./apis
go work sync
test -s /home/mschuppe/src/github.com/openstack-k8s-operators/infra-operator/bin/controller-gen || GOBIN=/home/mschuppe/src/github.com/openstack-k8s-operators/infra-operator/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.10.0
/home/mschuppe/src/github.com/openstack-k8s-operators/infra-operator/bin/controller-gen rbac:roleName=manager-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases && \
rm -f apis/bases/* && cp -a config/crd/bases apis/
/home/mschuppe/src/github.com/openstack-k8s-operators/infra-operator/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
# github.com/openstack-k8s-operators/lib-common/modules/test/helpers
../../../../go/pkg/mod/github.com/openstack-k8s-operators/lib-common/modules/test@v0.1.0/helpers/memcached.go:85:26: cannot use mc.Spec.Replicas (variable of type *int32) as type int32 in assignment
../../../../go/pkg/mod/github.com/openstack-k8s-operators/lib-common/modules/test@v0.1.0/helpers/memcached.go:89:23: cannot convert mc.Spec.Replicas (variable of type *int32) to type int
gmake: *** [Makefile:104: vet] Error 2
```

**Comment by stuggi** [comment]
this one changed it https://github.com/openstack-k8s-operators/infra-operator/commit/c906ec209d92f13820154aba219876aed877d757 https://github.com/openstack-k8s-operators/infra-operator/pull/80. should we revert?

**Comment by gibizer** [comment]
We merged a fix in lib-common/modules/test and tagged it v0.1.1. Now I'm bumping to it here to make the build pass

**Review by abays — APPROVED** [review]
/lgtm

**Pull request merged**
