### PR TITLE
Make the network names case insensitive

### PR DESCRIPTION
**Pull request by rabi**
This could be a temporary change to make dataplane networks small case and align with what we use in
control plane network attachments etc or permanent if we want to make networks/subnets case in-sensitive.

### CODE REVIEW

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
multinode job failed with `error: unable to default to a user name: the server is currently unable to handle the request (get users.user.openshift.io ~`

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
recheck

**Review by stuggi — APPROVED** [review]
/lgtm

**Comment by rabi** [comment]
Looks like failing building bundle.

[2/3] STEP 7/8: RUN /workspace/csv-merger   --import-env-files=/bundle_extra_data/env-vars.yaml   --dataplane-csv=/bundle_extra_data/manifests/dataplane-operator.clusterserviceversion.yaml   --base-csv=/manifests/openstack-operator.clusterserviceversion.yaml | tee /openstack-operator.clusterserviceversion.yaml.new
open /bundle_extra_data/env-vars.yaml: no such file or directorygoroutine 1 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
main.exitWithError({0xc00047a900?, 0xe713fb?})
	/workspace/csv-merger.go:71 +0x33
main.getEnvsFromFile({0x7fff5374ae51?, 0x20?})
	/workspace/csv-merger.go:41 +0x47
main.main()
	/workspace/csv-merger.go:165 +0x650

**Comment by rabi** [comment]
recheck tempest failed with neutron not available

**Comment by rabi** [comment]
recheck

**Comment by rabi** [comment]
let's see if removing depends-on helps.. I can't see why it should fail.

**Comment by rabi** [comment]
recheck

**Review by stuggi — APPROVED** [review]
/lgtm

**Pull request merged**
