### PR TITLE
Remove OpenStackClient CR

### PR DESCRIPTION
**Pull request by kajinamit**
OpenStackClient CR requires KeystoneAPI CR, but this causes circular dependencies between infra-operator and keystone-operator because KeystoneAPI requires Memcached CR which is provided by infra-operator.

This removes the OpenStackClient CR, so that we can move it to keystone-operator and resolves that circular dependency.

### CODE REVIEW

**Comment by kajinamit** [comment]
It seems we have to merge https://github.com/openstack-k8s-operators/openstack-operator/pull/397 so that we can remove the CR.

**Comment by abays** [comment]
Could you also remove the `Makefile` comments referencing the client webhooks?

**Comment by abays** [comment]
This will not be able to pass CI, so we might have to force-merge it:

```
github.com/openstack-k8s-operators/openstack-operator imports
	github.com/openstack-k8s-operators/infra-operator/apis/client/v1beta1: module github.com/openstack-k8s-operators/infra-operator/apis@latest found (v0.0.0-20230717054643-27820dc98d9b, replaced by github.com/kajinamit/infra-operator/apis@v0.0.0-20230718052631-8a6d54cb9c61), but does not contain package github.com/openstack-k8s-operators/infra-operator/apis/client/v1beta1
```

**Comment by abays** [comment]
> This will not be able to pass CI, so we might have to force-merge it:
> 
> ```
> github.com/openstack-k8s-operators/openstack-operator imports
> 	github.com/openstack-k8s-operators/infra-operator/apis/client/v1beta1: module github.com/openstack-k8s-operators/infra-operator/apis@latest found (v0.0.0-20230717054643-27820dc98d9b, replaced by github.com/kajinamit/infra-operator/apis@v0.0.0-20230718052631-8a6d54cb9c61), but does not contain package github.com/openstack-k8s-operators/infra-operator/apis/client/v1beta1
> ```

Maybe it will now that we merged https://github.com/openstack-k8s-operators/openstack-operator/pull/397

/test infra-operator-build-deploy

**Comment by abays** [comment]
recheck

**Comment by abays** [comment]
recheck

**Comment by kajinamit** [comment]
recheck

I guess the problem was fixed by https://github.com/openstack-k8s-operators/install_yamls/pull/413 .

**Comment by abays** [comment]
> recheck
> 
> I guess the problem was fixed by [openstack-k8s-operators/install_yamls#413](https://github.com/openstack-k8s-operators/install_yamls/pull/413) .

There's a new problem that was introduced that we're now trying to fix:

```
fatal: destination path 'infra-operator' already exists and is not an empty directory.\nmake[1]: *** [Makefile:675: netconfig_deploy_prep] Error 128
```

**Comment by abays** [comment]
> > recheck
> > I guess the problem was fixed by [openstack-k8s-operators/install_yamls#413](https://github.com/openstack-k8s-operators/install_yamls/pull/413) .
> 
> There's a new problem that was introduced that we're now trying to fix:
> 
> ```
> fatal: destination path 'infra-operator' already exists and is not an empty directory.\nmake[1]: *** [Makefile:675: netconfig_deploy_prep] Error 128
> ```

We merged https://github.com/openstack-k8s-operators/install_yamls/pull/417, so hopefully this can pass CI

**Comment by abays** [comment]
recheck

**Review by gibizer — APPROVED** [review]
looks sane

**Pull request merged**
