### PR TITLE
Ensure nodeSelector logic is consistent for all operators

### PR DESCRIPTION
**Pull request by olliewalsh**
nodeSelectors are not currently applied consistently across all operators.

Some do not support nodeSelectors at all - will be implemented in this series of pull requests.
Some do not apply them to every pod (jobs/cronjobs esp) - will be resolved in this series of pull requests.
Some do not apply a node selector update correctly, only when not initially set.
Some support nodeSelectors but do not inherit the default nodeSelector from the OpenstackControlPlane CR.

Jira: [OSPRH-10734](https://issues.redhat.com//browse/OSPRH-10734)

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by abays** [comment]
> Build failed (check pipeline). Post `recheck` (without leading slash) to rerun all jobs. Make sure the failure cause has been resolved before you rerun jobs.
> 
> https://softwarefactory-project.io/zuul/t/rdoproject.org/buildset/4f94987b6da342a79d89e2c82fcb9afc
> 
> ❌ [openstack-k8s-operators-content-provider ](https://softwarefactory-project.io/zuul/t/rdoproject.org/build/957957f51b104279a797f8c364d4b5cf) **FAILURE** in 11m 42s ⚠️ [podified-multinode-edpm-deployment-crc ](https://softwarefactory-project.io/zuul/t/rdoproject.org/build/ec1a5ade129341b4b29df0d5333310fd) SKIPPED Skipped due to failed job openstack-k8s-operators-content-provider ⚠️ [cifmw-crc-podified-edpm-baremetal ](https://softwarefactory-project.io/zuul/t/rdoproject.org/build/8abe6fa610b9440ca1efe12abe9c9e63) SKIPPED Skipped due to failed job openstack-k8s-operators-content-provider

I think the error is legitimate:

```
    # github.com/openstack-k8s-operators/openstack-operator/pkg/openstack
    pkg/openstack/dnsmasq.go:48:32: cannot use instance.Spec.NodeSelector (variable of type map[string]string) as *map[string]string value in assignment
    Error: building at STEP "RUN if [ -f $CACHITO_ENV_FILE ] ; then source $CACHITO_ENV_FILE ; fi ; env ${GO_BUILD_EXTRA_ENV_ARGS} go build ${GO_BUILD_EXTRA_ARGS} -a -o ${DEST_ROOT}/manager main.go": while running runtime: exit status 1
    make: *** [Makefile:209: docker-build] Error 1
```

**Comment by olliewalsh** [comment]
> > Build failed (check pipeline). Post `recheck` (without leading slash) to rerun all jobs. Make sure the failure cause has been resolved before you rerun jobs.
> > https://softwarefactory-project.io/zuul/t/rdoproject.org/buildset/4f94987b6da342a79d89e2c82fcb9afc
> > ❌ [openstack-k8s-operators-content-provider ](https://softwarefactory-project.io/zuul/t/rdoproject.org/build/957957f51b104279a797f8c364d4b5cf) **FAILURE** in 11m 42s ⚠️ [podified-multinode-edpm-deployment-crc ](https://softwarefactory-project.io/zuul/t/rdoproject.org/build/ec1a5ade129341b4b29df0d5333310fd) SKIPPED Skipped due to failed job openstack-k8s-operators-content-provider ⚠️ [cifmw-crc-podified-edpm-baremetal ](https://softwarefactory-project.io/zuul/t/rdoproject.org/build/8abe6fa610b9440ca1efe12abe9c9e63) SKIPPED Skipped due to failed job openstack-k8s-operators-content-provider
> 
> I think the error is legitimate:
> 
> ```
>     # github.com/openstack-k8s-operators/openstack-operator/pkg/openstack
>     pkg/openstack/dnsmasq.go:48:32: cannot use instance.Spec.NodeSelector (variable of type map[string]string) as *map[string]string value in assignment
>     Error: building at STEP "RUN if [ -f $CACHITO_ENV_FILE ] ; then source $CACHITO_ENV_FILE ; fi ; env ${GO_BUILD_EXTRA_ENV_ARGS} go build ${GO_BUILD_EXTRA_ARGS} -a -o ${DEST_ROOT}/manager main.go": while running runtime: exit status 1
>     make: *** [Makefile:209: docker-build] Error 1
> ```

circular dependency so expected to fail until openstack-operator is updated to use the ptr for nodeSelector

**Comment by stuggi** [comment]
we need to get https://github.com/openstack-k8s-operators/infra-operator/pull/311 landed. lets hold until we get this in

**Pull request merged**
