### PR TITLE
Remove service overrides for kuttl tests which don't have network-isolation

### PR DESCRIPTION
**Pull request by stuggi**

### CODE REVIEW

**Comment by stuggi** [comment]
for reference https://github.com/openstack-k8s-operators/openstack-operator/blob/main/kuttl-test.yaml#L21

**Comment by stuggi** [comment]
recheck

**Comment by stuggi** [comment]
recheck

**Comment by karelyatin** [comment]
recheck retry limit

**Comment by karelyatin** [comment]
/lgtm 
worked fine in test https://github.com/openstack-k8s-operators/openstack-operator/pull/1230

**Pull request merged**
