### PR TITLE
Merge test file directory

### PR DESCRIPTION
**Pull request by kajinamit**
This repository currently have the two directories to maintain test resources('test' and 'tests') but this is confusing. Let's merge these to into a single one.

### CODE REVIEW

**Comment by kajinamit** [comment]
recheck

**Comment by stuggi** [comment]
this PR is not merging the directories, just doing a change in the Makefile, is that expected?

**Comment by kajinamit** [comment]
> this PR is not merging the directories, just doing a change in the Makefile, is that expected?

Hmm it's wired. It seems `git mv` was not properly included. Let me fix it now ...

**Comment by stuggi** [comment]
in infra-operator, heat-operator its now `/tests` directory, in placement, node it is `/test` . might want to align there as well

**Review by stuggi — APPROVED** [review]
/lgtm

**Comment by kajinamit** [comment]
> in infra-operator, heat-operator its now `/tests` directory, in placement, nova it is `/test` (not checked all others). might want to align there as well

Yeah. For now I'm renaming the directory in placement-operator by https://github.com/openstack-k8s-operators/placement-operator/pull/24 (it's a good timing because we can't directly rename kuttl directory once we add the reference to install_yamls Makefile).

**Comment by kajinamit** [comment]
recheck

**Pull request merged**
