### PR TITLE
Support disconnected network environments

### PR DESCRIPTION
**Pull request by dprince**
This PR adds support for installing the operator in disconnected network environments. To build with image-digests set USE_IMAGE_DIGESTS=true before running make bundle.

For Prow jobs we are enabling this via .prow-ci.env

This drops the old logic from create_bundle.sh which has been broken with operator-sdk's make bundle for some time.

(NOTE: this currently requires a secure registry)

### CODE REVIEW

**Comment by abays** [comment]
> @dprince: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> Test name 	Commit 	Details 	Required 	Rerun command
> ci/prow/infra-operator-build-deploy-kuttl 	[9e42ece](https://github.com/openstack-k8s-operators/infra-operator/commit/9e42ece20e492f369e0fd36a142537580ef60a0d) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_infra-operator/111/pull-ci-openstack-k8s-operators-infra-operator-main-infra-operator-build-deploy-kuttl/1694698130672455680) 	true 	`/test infra-operator-build-deploy-kuttl`
> 
> [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=infra-operator&pr=111). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:dprince).

@dprince It looks like we might need to add some extra creds to CI so that it's able to pull from `registry.redhat.io` for the Redis image:

```
time="2023-08-24T13:23:22Z" level=fatal msg="Error generating bundle manifests: error resolving image: GET https://registry.redhat.io/auth/realms/rhcc/protocol/redhat-docker-v2/auth?scope=repository%3Arhel9%2Fredis-6%3Apull&service=docker-registry: UNAUTHORIZED: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication"
```

**Comment by dprince** [comment]
> > @dprince: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:
> > Test name 	Commit 	Details 	Required 	Rerun command
> > ci/prow/infra-operator-build-deploy-kuttl 	[9e42ece](https://github.com/openstack-k8s-operators/infra-operator/commit/9e42ece20e492f369e0fd36a142537580ef60a0d) 	[link](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openstack-k8s-operators_infra-operator/111/pull-ci-openstack-k8s-operators-infra-operator-main-infra-operator-build-deploy-kuttl/1694698130672455680) 	true 	`/test infra-operator-build-deploy-kuttl`
> > [Full PR test history](https://prow.ci.openshift.org/pr-history?org=openstack-k8s-operators&repo=infra-operator&pr=111). [Your PR dashboard](https://prow.ci.openshift.org/pr?query=is:pr+state:open+author:dprince).
> 
> @dprince It looks like we might need to add some extra creds to CI so that it's able to pull from `registry.redhat.io` for the Redis image:
> 
> ```
> time="2023-08-24T13:23:22Z" level=fatal msg="Error generating bundle manifests: error resolving image: GET https://registry.redhat.io/auth/realms/rhcc/protocol/redhat-docker-v2/auth?scope=repository%3Arhel9%2Fredis-6%3Apull&service=docker-registry: UNAUTHORIZED: Please login to the Red Hat Registry using your Customer Portal credentials. Further instructions can be found here: https://access.redhat.com/RegistryAuthentication"
> ```

I checked and we should be enheriting these creds from the openstack-k8s-operators Github Organization. Additionally we are calling the redhat-actions/podman-login@v1 in the create bundle workflow. Maybe our credentials expired or something?

**Comment by abays** [comment]
recheck

**Comment by dprince** [comment]
Added an extra 'skopeo inspect' command to the create_bundle.sh to see if that works. That would verify that the credentials are working

**Comment by dprince** [comment]
This will require operator-sdk-1.31. I bumped the .github action version and verified it. For prow jobs we'll probably need https://github.com/openshift/release/pull/42826 to get it passing.

**Comment by abays** [comment]
https://github.com/openshift/release/pull/42826 merged

/test infra-operator-build-deploy-kuttl

**Comment by abays** [comment]
recheck

**Comment by abays** [comment]
recheck

**Comment by abays** [comment]
recheck

**Review by abays — APPROVED** [review]
/lgtm

**Review by fmount — APPROVED** [review]
In line with what already merged in the service operators

**Pull request merged**
