### PR TITLE
Run dnsmasq not as privileged user

### PR DESCRIPTION
**Pull request by stuggi**
Jira: [OSPRH-10853](https://issues.redhat.com//browse/OSPRH-10853)

### CODE REVIEW

**Review by abays — APPROVED** [review]
/lgtm

**Comment by stuggi** [comment]
Warning  FailedAttachVolume  2s (x12 over 8m21s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-c9af9cec-bbe0-457e-bac9-9a7b97a12e5a" : rpc error: code = Internal desc = [ControllerPublishVolume] get volume failed with error Get "https://volume.rdo.mtl2.vexxhost.net/v3/5e292ffab8d841578fde5aa9811400be/volumes/d987a168-ae50-434e-8c7e-0eeadb5f610e": dial tcp 38.102.83.252:443: connect: connection refused

**Pull request merged**
