### PR TITLE
Ensure we don't append to nil routes

### PR DESCRIPTION
**Pull request by rabi**
Also, handle ipv6 scenario.

### CODE REVIEW

**Comment by rabi** [comment]
recheck RETRY_LIMIT

**Comment by rabi** [comment]
Failed to run 'make crc_storage' target. Aborting

**Review by stuggi — APPROVED** [review]
/lgtm 

Thanks Rabi, this should prevent the panic in https://github.com/openstack-k8s-operators/infra-operator/issues/200

**Pull request merged**
