### PR TITLE
This change adds requirements for FIPS

### PR DESCRIPTION
**Pull request by bshephar**
This change ensures the infra-operator is built with FIPS compliance.

### CODE REVIEW

**Comment by abays** [comment]
recheck

**Review by abays — APPROVED** [review]
/lgtm

**Comment by abays** [comment]
recheck

**Comment by gibizer** [comment]
rebased and adapated it to golang 1.20

**Comment by gibizer** [comment]
Content provider still failing. We probably need to land https://github.com/openstack-k8s-operators/openstack-operator/pull/668 first

**Comment by gibizer** [comment]
recheck

**Comment by gibizer** [comment]
https://github.com/openstack-k8s-operators/openstack-operator/pull/668 merged so hopefully it helps here too

**Comment by gibizer** [comment]
/test infra-operator-build-deploy-kuttl

The other two kuttl tests passed so this probably some race
```
=== CONT  kuttl/harness/redis
    logger.go:42: 14:02:04 | redis | Skipping creation of user-supplied namespace: infra-kuttl-tests
    logger.go:42: 14:02:04 | redis/1-deploy-redis | starting test step 1-deploy-redis
    case.go:364: failed in step 1-deploy-redis
    case.go:366: Internal error occurred: failed calling webhook "mredis.kb.io": failed to call webhook: Post "https://infra-operator-controller-manager-service.openstack-operators.svc:443/mutate-redis-openstack-org-v1beta1-redis?timeout=10s": dial tcp 10.129.0.81:9443: connect: connection refused
```

**Pull request merged**
